---
title: "Data Manipulation"
author: "Diana Ballesteros"
date: "9/20/2018" 
output: html_document
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


##
```{r}

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)


```

##Select Variables 

```{r}

select(litters_data, group, litter_number, gd0_weight, pups_survive)

```

....by specifying a range: 
```{r}
select(litters_data, gd_df_birth:pups_survive)
select(litters_data, group, litter_number, gd0_weight, pups_survive)
```


...by saying you want to remove (this will allow you to remove a column you don't want): 
```{r}
select(litters_data, -litter_number)
```

...Selecting gd_day_0_weight and also renaming it as well. You can do either. 
```{r}
select(litters_data, group, litter_number, gd_day_0_weight = gd0_weight)
rename(litters_data,  gd_day_0_weight = gd0_weight)
```

....use select helpers

```{r}
?select_helpers

select(litters_data, starts_with("gd"))
select(litters_data, litter_numer, starts_with("pup"))

select(litters_data, litter_number, everything())
```

